### ISSUE TITLE
Need onPageSelected listener

### ISSUE THREAD

**Issue by PriyankaKamthe** [Crysis21/PagerTabIndicator#1]
I need to change tab text on page selection change, so for that i need listener to set updated text on page change. I don't know how to implement this using PagerTabIndicator.
Previously I was using **com.astuetz.PagerSlidingTabStrip** but since Its giving problem in Android studio 3.0 so I switched to **com.hold1:pagertabindicator:1.0.2**. 
In PagerSlidingTabStrip there is listener called **setOnPageChangeListener**  which having 3 methods by using them I am able to change tab text dynamically on page change. but now i need to implement same by using **com.hold1:pagertabindicator:1.0.2**.

**Comment by Crysis21** [comment]
The reason this method is missing is because is not needed anymore. The listener you passed before to PagerSlidingTabStrip, should be set directly to the ViewPager now. Use method `addOnPageChangeListener` to set you listener to ViewPager.

The reason you should do this, is because ViewPager supports multiple listeners now. Let me know if this solved your issue.

**Comment by PriyankaKamthe** [comment]
now I set `addOnPageChangeListener` to ViewPager & after running application Its giving following error;
```
 java.lang.ArithmeticException: divide by zero
at com.hold1.pagertabsindicator.PagerTabsIndicator.onLayout(PagerTabsIndicator.java:185)
at android.view.View.layout(View.java:17637)
 at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
 at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1192)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
 at android.view.View.layout(View.java:17637)
at android.view.ViewGroup.layout(ViewGroup.java:5575)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
at android.view.Choreographer.doCallbacks(Choreographer.java:686)
at android.view.Choreographer.doFrame(Choreographer.java:621)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
```

**Comment by Crysis21** [comment]
Thanks for the report. the crash was my fault for not checking correctly if the tab bar has attached views yet.

Can you update to the latest version:
`compile 'com.hold1:pagertabindicator:1.0.5'`

Also please write the code of you setup so I can have a better idea of the problem. Typically you should:
1. create the viewpager
2. create adapter
3. add adapter to viewpager
4. add viewpager to tabs indicator.

Thanks.

**Comment by PriyankaKamthe** [comment]
Now i change in gradle with `compile 'com.hold1:pagertabindicator:1.0.5'`
But Facing problem with this code;
```
LinearLayout mTabsLinearLayout = (LinearLayout) mTabStrip.getChildAt(0);
        for (int i = 0; i < mTabsLinearLayout.getChildCount(); i++) {
           TextView tv = (TextView) mTabsLinearLayout.getChildAt(i);
            if (i == index) {
                tv.setTextColor(getResources().getColor(R.color.colorPrimary));
            } else {
                tv.setTextColor(Color.BLACK);
            }
        }
```
Following is issue;
 ```
java.lang.ClassCastException: com.hold1.pagertabsindicator.TabView cannot be cast to android.widget.TextView
at com.retail.Activities.TrackTransactionOptionsActivity$1.onPageSelected(TrackTransactionOptionsActivity.java:159)
at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1938)
```

**Comment by Crysis21** [comment]
PagerTabIndicator wraps it's chid in a TabView component, to provide offset callback useful for animations. You can check for example my demo app, in CustomAnim adapter to check how the active color is fading on a tab.

Given so, the quick fix for your problem is to ask the child view (your textview in this case) from the TabView:
`           TextView tv = (TextView) mTabsLinearLayout.getChildAt(i).getChildAt(0);
`

I will improve this aspect of the indictor with optional wrapping in TabView

**Comment by PriyankaKamthe** [comment]
for changing text color of tab text dynamically I used `mTabStrip.setTextColor(Color.BLACK);`
but When i tried to run application Its giving me following error; but When I run application in debug mode its runs perfectly.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
at com.hold1.pagertabsindicator.PagerTabsIndicator.drawIndicator(PagerTabsIndicator.java:332)
at com.hold1.pagertabsindicator.PagerTabsIndicator.onDraw(PagerTabsIndicator.java:317)
at android.view.View.draw(View.java:17185)
at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1643)
at android.view.View.updateDisplayListIfDirty(View.java:16167)
at android.view.View.draw(View.java:16951)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16162)
at android.view.View.draw(View.java:16951)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16162)
at android.view.View.draw(View.java:16951)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16162)
at android.view.View.draw(View.java:16951)
```
