### ISSUE TITLE
NullPointerException  for  'int android.view.View.getLeft()'

### ISSUE THREAD

**Issue by PriyankaKamthe** [Crysis21/PagerTabIndicator#2]
When i tried to run application Its giving me following error; but When I run application in debug mode its runs perfectly.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
at com.hold1.pagertabsindicator.PagerTabsIndicator.drawIndicator(PagerTabsIndicator.java:332)
at com.hold1.pagertabsindicator.PagerTabsIndicator.onDraw(PagerTabsIndicator.java:317)
at android.view.View.draw(View.java:17185)
at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1643)
at android.view.View.updateDisplayListIfDirty(View.java:16167)
at android.view.View.draw(View.java:16951)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16162)
at android.view.View.draw(View.java:16951)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16162)
at android.view.View.draw(View.java:16951)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16162)
at android.view.View.draw(View.java:16951)
```
Following is way i implement PagerTabsIndicator;
In xml;
```
<com.hold1.pagertabsindicator.PagerTabsIndicator
        android:id="@+id/transactionTabs"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_alignParentBottom="true"
        android:background="#FBE9E9EC"
        app:tab_indicator="bottom_bar"
        app:tab_indicator_bg_color="#FBE9E9EC"
        app:tab_lock_expanded="true"
        app:tab_divider_color="@color/colorPrimary"
        app:tab_indicator_color="@color/drawerBgColor"
        app:tab_indicator_height="80dp"
        />
```
In Activity;
 ```
tabPagerAdapter = new TransactionTabPagerAdapter(getSupportFragmentManager(),userTransactionResDTO,this);
mPager.setAdapter(tabPagerAdapter);
mTabStrip.setViewPager(mPager);
```
To change Tab text color dynamically I used;
```
if (position==0) {
mTabStrip.setTextColor(getResources().getColor(R.color.colorPrimary));
 } else {
mTabStrip.setTextColor(Color.BLACK);
}
```
In gradle;
 `compile 'com.hold1:pagertabindicator:1.0.5'`

**Comment by Crysis21** [comment]
There are some things I need to understand about this crash log. What do you mean in debug works vs production? Is you PagerAdapter creating tabs dynamically? (Does it get a config at runtime and generated the tabs after loading data?)

To change any property you have to call `refresh()` after it. I will provide a full documentation, until then you can use the sample app code to check. For example:

`mTabStrip.setTextColor(getResources().getColor(R.color.colorPrimary)).refresh();` would change the text color.

I also added a null-check to prevent the above crash in 1.0.6

`compile 'com.hold1:pagertabindicator:1.0.6'`

**Comment by PriyankaKamthe** [comment]
Thanks, `compile 'com.hold1:pagertabindicator:1.0.6'` solved my issue.
